"use strict";
exports.LibraryName = "botbuilder-location";
exports.Strings = {
    "AddressSeparator": "AddressSeparator",
    "AddToFavoritesAsk": "AddToFavoritesAsk",
    "AskForEmptyAddressTemplate": "AskForEmptyAddressTemplate",
    "AskForPrefix": "AskForPrefix",
    "AskForTemplate": "AskForTemplate",
    "CancelPrompt": "CancelPrompt",
    "ConfirmationAsk": "ConfirmationAsk",
    "Country": "Country",
    "DefaultPrompt": "DefaultPrompt",
    "EnterNewFavoriteLocationName": "EnterNewFavoriteLocationName",
    "FavoriteAddedConfirmation": "FavoriteAddedConfirmation",
    "HelpMessage": "HelpMessage",
    "InvalidLocationResponse": "InvalidLocationResponse",
    "InvalidLocationResponseFacebook": "InvalidLocationResponseFacebook",
    "LocationNotFound": "LocationNotFound",
    "Locality": "Locality",
    "MultipleResultsFound": "MultipleResultsFound",
    "PostalCode": "PostalCode",
    "Region": "Region",
    "ResetPrompt": "ResetPrompt",
    "SingleResultFound": "SingleResultFound",
    "StreetAddress": "StreetAddress",
    "TitleSuffixFacebook": "TitleSuffixFacebook",
    "TitleSuffix": "TitleSuffix",
};
