"use strict";
exports.LibraryName = "botbuilder-location";
exports.Strings = {
    "AddressSeparator": exports.LibraryName + ":AddressSeparator",
    "AskForEmptyAddressTemplate": exports.LibraryName + ":AskForEmptyAddressTemplate",
    "AskForPrefix": exports.LibraryName + ":AskForPrefix",
    "AskForTemplate": exports.LibraryName + ":AskForTemplate",
    "CancelPrompt": exports.LibraryName + ":CancelPrompt",
    "ConfirmationAsk": exports.LibraryName + ":ConfirmationAsk",
    "Country": exports.LibraryName + ":Country",
    "DefaultPrompt": exports.LibraryName + ":DefaultPrompt",
    "HelpMessage": exports.LibraryName + ":HelpMessage",
    "InvalidLocationResponse": exports.LibraryName + ":InvalidLocationResponse",
    "InvalidLocationResponseFacebook": exports.LibraryName + ":InvalidLocationResponseFacebook",
    "LocationNotFound": exports.LibraryName + ":LocationNotFound",
    "Locality": exports.LibraryName + ":Locality",
    "MultipleResultsFound": exports.LibraryName + ":MultipleResultsFound",
    "PostalCode": exports.LibraryName + ":PostalCode",
    "Region": exports.LibraryName + ":Region",
    "ResetPrompt": exports.LibraryName + ":ResetPrompt",
    "SingleResultFound": exports.LibraryName + ":SingleResultFound",
    "StreetAddress": exports.LibraryName + ":StreetAddress",
    "TitleSuffixFacebook": exports.LibraryName + ":TitleSuffixFacebook",
    "TitleSuffix": exports.LibraryName + ":TitleSuffix",
};
