//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Bot.Builder.Location.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Bot.Builder.Location.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string AddressSeparator {
            get {
                return ResourceManager.GetString("AddressSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK {0}. Please also provide the country..
        /// </summary>
        internal static string AskForCountry {
            get {
                return ResourceManager.GetString("AskForCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK {0}. Please also provide the city or locality..
        /// </summary>
        internal static string AskForLocality {
            get {
                return ResourceManager.GetString("AskForLocality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK {0}. Please also provide the zip or postal code..
        /// </summary>
        internal static string AskForPostalCode {
            get {
                return ResourceManager.GetString("AskForPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK {0}. Please also provide the region..
        /// </summary>
        internal static string AskForRegion {
            get {
                return ResourceManager.GetString("AskForRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK {0}. Please also provide the street address..
        /// </summary>
        internal static string AskForStreetAddress {
            get {
                return ResourceManager.GetString("AskForStreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string CancelCommand {
            get {
                return ResourceManager.GetString("CancelCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, cancelled..
        /// </summary>
        internal static string CancelPrompt {
            get {
                return ResourceManager.GetString("CancelPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, I will ship to {0}..
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, I will ship to {0}. Is that correct? Enter &apos;yes&apos; or &apos;no&apos;..
        /// </summary>
        internal static string ConfirmationAsk {
            get {
                return ResourceManager.GetString("ConfirmationAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t understand. Enter &apos;yes&apos; or &apos;no&apos;..
        /// </summary>
        internal static string ConfirmationInvalidResponse {
            get {
                return ResourceManager.GetString("ConfirmationInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string HelpCommand {
            get {
                return ResourceManager.GetString("HelpCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The help message.
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type or say a number to choose the address, or enter &apos;cancel&apos; to exit..
        /// </summary>
        internal static string InvalidLocationResponse {
            get {
                return ResourceManager.GetString("InvalidLocationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on Send Location to proceed; type or say cancel to exit..
        /// </summary>
        internal static string InvalidLocationResponseFacebook {
            get {
                return ResourceManager.GetString("InvalidLocationResponseFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wasn&apos;t able to find this address. Try again..
        /// </summary>
        internal static string LocationNotFound {
            get {
                return ResourceManager.GetString("LocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I found these results. Type or say a number to choose the address, or enter &apos;other&apos; to select another address..
        /// </summary>
        internal static string MultipleResultsFound {
            get {
                return ResourceManager.GetString("MultipleResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        internal static string OtherComand {
            get {
                return ResourceManager.GetString("OtherComand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        internal static string ResetCommand {
            get {
                return ResourceManager.GetString("ResetCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, let&apos;s start over..
        /// </summary>
        internal static string ResetPrompt {
            get {
                return ResourceManager.GetString("ResetPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a location.
        /// </summary>
        internal static string SelectLocation {
            get {
                return ResourceManager.GetString("SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I found this result. Is this the correct address?.
        /// </summary>
        internal static string SingleResultFound {
            get {
                return ResourceManager.GetString("SingleResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Type or say an address..
        /// </summary>
        internal static string TitleSuffix {
            get {
                return ResourceManager.GetString("TitleSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tap &apos;Send Location&apos; to choose an address..
        /// </summary>
        internal static string TitleSuffixFacebook {
            get {
                return ResourceManager.GetString("TitleSuffixFacebook", resourceCulture);
            }
        }
    }
}
